version: 1
runtime: custom
vm: true
api_version: 1

manual_scaling:
  instances: 1
  
vm_settings:
  machine_type: f1-micro
  forwarded_ports: 3000
 
vm_health_check:
  enable_health_check: False

handlers:
- url: .*
  script: nothing.js
